# Generated by Django 2.1.5 on 2019-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='images/image_headers')),
                ('status', models.CharField(choices=[('Draft', 'D'), ('Published', 'P')], max_length=9)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
